/*
-*- coding: utf-8 -*-
* vim: set ts=4 sw=4 et sts=4 ai:
* Copyright 2013 MITHIS
* All rights reserved.
*/

/*global module*/

// game resources
// in the case of the items, set their image name equal to their type.
var assets = module.exports = [{
    name: 'outline',
    type: 'image',
    src: '/_common/img/render/outline.png'
}, {
    name: 'selector',
    type: 'image',
    src: '/_common/img/render/selector.png'
}, {
    name: 'pause-icon',
    type: 'image',
    src: '/_common/img/render/pause-icon.png'
}, {
    name: 'weapon',
    type: 'image',
    src: '/_common/img/render/weapon_01.png'
}, {
    name: 'engine',
    type: 'image',
    src: '/_common/img/render/engine_01.png'
}, {
    name: 'power',
    type: 'image',
    src: '/_common/img/render/power_01.png'
}, {
    name: 'console',
    type: 'image',
    src: '/_common/img/render/console_02.png'
}, {
    name: 'component',
    type: 'image',
    src: '/_common/img/render/components_01.png'
}, {
    name: 'door',
    type: 'image',
    src: '/_common/img/render/door_01.png'
}, {
    name: 'wall',
    type: 'image',
    src: '/_common/img/render/wall_001.png'
}, {
    name: 'weakspot',
    type: 'image',
    src: '/_common/img/render/weakspot.png'
}, {
    name: 'teleporter',
    type: 'image',
    src: '/_common/img/render/teleporter.png'
}, {
    name: 'metatiles32x32',
    type: 'image',
    src: '/_common/img/render/metatiles32x32.png'
}, {
    name: 'area_01',
    type: 'tmx',
    src: '/_common/outlines/small.tmx'
}, {
    name: 'test',
    type: 'tmx',
    src: '/_common/outlines/test.tmx'
}, {
    name: 'cyborg_frigate',
    type: 'tmx',
    src: '/_common/outlines/cyborg_frigate.tmx'
}, {
    name: 'cyborg_frigate_img',
    type: 'image',
    src: '/_common/img/render/ships/cyborg/cyborg_frigate_img.png'
}, {
    name: 'cyborg_cruiser',
    type: 'tmx',
    src: '/_common/outlines/cyborg_cruiser.tmx'
}, {
    name: 'cyborg_cruiser_img',
    type: 'image',
    src: '/_common/img/render/ships/cyborg/cyborg_cruiser_img.png'
}, {
    name: 'cyborg_battleship1',
    type: 'tmx',
    src: '/_common/outlines/cyborg_battleship1.tmx'
}, {
    name: 'cyborg_battleship1_img',
    type: 'image',
    src: '/_common/img/render/ships/cyborg/cyborg_battleship1_img.png'
}, {
    name: 'cyborg_battleship2',
    type: 'tmx',
    src: '/_common/outlines/cyborg_battleship2.tmx'
}, {
    name: 'cyborg_battleship2_img',
    type: 'image',
    src: '/_common/img/render/ships/cyborg/cyborg_battleship2_img.png'
}, {
    name: 'cyborg_drone',
    type: 'tmx',
    src: '/_common/outlines/cyborg_drone.tmx'
}, {
    name: 'cyborg_drone_img',
    type: 'image',
    src: '/_common/img/render/ships/cyborg/cyborg_drone_img.png'
}, {
    name: 'humanoid_frigate',
    type: 'tmx',
    src: '/_common/outlines/humanoid_frigate.tmx'
}, {
    name: 'humanoid_frigate_img',
    type: 'image',
    src: '/_common/img/render/ships/humanoid/humanoid_frigate_img.png'
}, {
    name: 'humanoid_cruiser',
    type: 'tmx',
    src: '/_common/outlines/humanoid_cruiser.tmx'
}, {
    name: 'humanoid_cruiser_img',
    type: 'image',
    src: '/_common/img/render/ships/humanoid/humanoid_cruiser_img.png'
}, {
    name: 'humanoid_battleship',
    type: 'tmx',
    src: '/_common/outlines/humanoid_battleship.tmx'
}, {
    name: 'humanoid_battleship_img',
    type: 'image',
    src: '/_common/img/render/ships/humanoid/humanoid_battleship_img.png'
}, {
    name: 'humanoid_drone',
    type: 'tmx',
    src: '/_common/outlines/humanoid_drone.tmx'
}, {
    name: 'humanoid_drone_img',
    type: 'image',
    src: '/_common/img/render/ships/humanoid/humanoid_drone_img.png'
}, {
    name: 'liquid_frigate',
    type: 'tmx',
    src: '/_common/outlines/liquid_frigate.tmx'
}, {
    name: 'liquid_frigate_img',
    type: 'image',
    src: '/_common/img/render/ships/liquid/liquid_frigate_img.png'
}, {
    name: 'liquid_cruiser',
    type: 'tmx',
    src: '/_common/outlines/liquid_cruiser.tmx'
}, {
    name: 'liquid_cruiser_img',
    type: 'image',
    src: '/_common/img/render/ships/liquid/liquid_cruiser_img.png'
}, {
    name: 'liquid_battleship',
    type: 'tmx',
    src: '/_common/outlines/liquid_battleship.tmx'
}, {
    name: 'liquid_battleship_img',
    type: 'image',
    src: '/_common/img/render/ships/liquid/liquid_battleship_img.png'
}, {
    name: 'liquid_drone',
    type: 'tmx',
    src: '/_common/outlines/liquid_drone.tmx'
}, {
    name: 'liquid_drone_img',
    type: 'image',
    src: '/_common/img/render/ships/liquid/liquid_drone_img.png'
}, {
    name: 'mechanoid_frigate',
    type: 'tmx',
    src: '/_common/outlines/mechanoid_frigate.tmx'
}, {
    name: 'mechanoid_frigate_img',
    type: 'image',
    src: '/_common/img/render/ships/mechanoid/mechanoid_frigate_img.png'
}, {
    name: 'mechanoid_cruiser',
    type: 'tmx',
    src: '/_common/outlines/mechanoid_cruiser.tmx'
}, {
    name: 'mechanoid_cruiser_img',
    type: 'image',
    src: '/_common/img/render/ships/mechanoid/mechanoid_cruiser_img.png'
}, {
    name: 'mechanoid_battleship',
    type: 'tmx',
    src: '/_common/outlines/mechanoid_battleship.tmx'
}, {
    name: 'mechanoid_battleship_img',
    type: 'image',
    src: '/_common/img/render/ships/mechanoid/mechanoid_battleship_img.png'
}, {
    name: 'mechanoid_drone',
    type: 'tmx',
    src: '/_common/outlines/mechanoid_drone.tmx'
}, {
    name: 'mechanoid_drone_img',
    type: 'image',
    src: '/_common/img/render/ships/mechanoid/mechanoid_drone_img.png'
}, {
    name: 'button',
    type: 'image',
    src: '/_common/img/render/button.png'
}, {
    name: 'creatures',
    type: 'image',
    src: '/_common/img/render/creatures.png'
}, {
    name: 'creatures_16x16',
    type: 'image',
    src: '/_common/img/render/creatures_16x16.png'
}, {
    name: 'star_hit_white',
    type: 'image',
    src: '/_common/img/render/star_hit_white.png'
}, {
    name: 'nothing',
    type: 'image',
    src: '/_common/img/render/nothing.png'
}, {
    name: 'projectile',
    type: 'image',
    src: '/_common/img/render/projectile.png'
}, {
    name: 'markers',
    type: 'image',
    src: '/_common/img/render/markers.png'
}, {
    name: 'charging-weapon-icon',
    type: 'image',
    src: '/_common/img/render/charging-weapon-icon.png'
}];
